routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes(['register' => false]);

Route::get('/dashboard', 'HomeController@dashboard')->name('dashboard');
Route::get('/', 'HomeController@index')->name('home');

/* Metingen */
Route::get('/rooms', 'MetingController@index')->name('metings.rooms');
Route::get('/metings/list', 'MetingController@list')->name('metings.list');
Route::get('/rooms/{room}', 'MetingController@room')->name('metings.room');
Route::post('/rooms/{room}', 'MetingController@room');
Route::get('/average', 'MetingController@average')->name('metings.average');
Route::resource('metings', 'MetingController');

/* Language */
Route::get('/language/{language}', 'UserController@setLanguage');

app/Meting.php
<?php

namespace App;

use Carbon\Carbon;
use App\Traits\GroupedLastScope;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Config;

class Meting extends Model
{
    use GroupedLastScope;

    protected $fillable = [
        'room', 'co2', 'temperature', 'humidity', 'tvoc',
    ];

    /**
     * Het aantal minuten sinds de laatste meting.
     */
    public function getTimeSinceLastAttribute(): int
    {
        return Carbon::parse($this->created_at)->diffInMinutes(Carbon::now());
    }

    /**
     * Hoe goed de CO2 waarde is.
     */
    public function getCo2GoodAttribute(): bool
    {
        return $this->co2 < config('constants.meting.co2_max');
    }

    /**
     * Hoe goed de vochtigheid is.
     */
    public function getHumidityGoodAttribute(): bool
    {
        return $this->humidity >= Config::get('constants.meting.humidity_min') && $this->humidity <= Config::get('constants.meting.humidity_max');
    }

    /**
     * Hoe goed de temperatuur  is.
     */
    public function getTemperatureGoodAttribute(): bool
    {
        return $this->temperature >= Config::get('constants.meting.temperature_min') && $this->temperature <= Config::get('constants.meting.temperature_max');
    }

    public static function getLatestByRoom($room): Meting
    {
        return Meting::where('room', $room)->latest()->first();
    }

    public static function getLatestAverage(): Meting
    {
        return Cache::remember('latest_average', 300, function () {
            $temp = Meting::interval('Realtime')->latest()->first();
            $avg = new Meting((array) $temp);
            $avg->created_at = $temp->created_at;

            return $avg;
        });
    }

    /**
     * Laatste meting by room(s) per interval.
     *
     * @param $rooms Integer || Array(Integer)
     * @param $interval String
     * @param $options [$period [Timestring, Timesting], $format Boolean ]
     *
     * @return Meting or Meting[]
     */
    public static function getPerIntervalByRoom($rooms, $interval, $options = null)
    {
        if (is_array($rooms)) {
            $result = [];
            foreach ($rooms as $room) {
                $latest = self::getPerIntervalByRoom($room, $interval, $options);
                $result[] = ['room' => $room, 'metingen' => $latest->values()];
            }

            return $result;
        }

        $room = $rooms;

        if (! empty($options['period'][0])) {
            $period = $options['period'];
        } else {
            $period = Meting::getPeriod($interval);
        }
        $format = $options['format'] ?? false;

        $metingen = Meting::where('room', $room)
            ->whereBetween(
                'created_at',
                [Carbon::createFromTimeString($period[0]), Carbon::createFromTimeString($period[1])]
            )->interval($interval)->latest()->take(15)->get()->reverse();

        if ($format) {
            return Meting::formatTimeStamps($metingen, $interval);
        }

        return $metingen;
    }

    /**
     * Laatste agg meting per interval
     * agg => aggregate => min/max/average.
     *
     * @return Meting
     */
    public static function getAllPerInterval($interval, $agg = 'avg', $period = null)
    {
        $_period = $period;

        //indien geen period meegegeven, zelf bepalen
        if (! $period[0]) {
            $_period = Meting::getPeriod($interval);
        }

        return Cache::remember("all_per_interval:${interval}:${agg}:".$_period[0].':'.$_period[1], 300, function () use ($interval, $agg, $_period) {
            return Meting::whereBetween(
                'created_at',
                [Carbon::createFromTimeString($_period[0]), Carbon::createFromTimeString($_period[1])]
            )->interval($interval, $agg)->latest()->take(15)->get()->reverse();
        });
    }

    /**
     * get period when not provided.
     *
     * FORMAT : Thu Apr 09 2020 00:00:00
     */
    public static function getPeriod($interval): array
    {
        switch ($interval) {
            case 'Hourly':
                return [Carbon::now()->subDays(2), Carbon::now()];
            case 'Daily':
                return [Carbon::now()->subWeeks(2), Carbon::now()];
            case 'Weekly':
                return [Carbon::now()->subWeeks(15), Carbon::now()];
            case 'Monthly':
                return [Carbon::now()->subMonths(10), Carbon::now()];
            default:
                return [Carbon::now()->subHours(4), Carbon::now()];
        }
    }

    /**
     * format timestamps.
     */
    public static function formatTimeStamps($metings, $interval)
    {
        switch ($interval) {
            case 'Realtime':
                $metings = $metings->map(function ($m) {
                    $m->created_at = \Carbon\Carbon::parse($m->created_at)->format('d/m/y - H:i');

                    return $m;
                });
                break;
            case 'Hourly':
                $metings = $metings->map(function ($m) {
                    $m->created_at = \Carbon\Carbon::parse($m->created_at)->format('d/m/y - H');

                    return $m;
                });
                break;
            case 'Daily':
            case 'Weekly':
                $metings = $metings->map(function ($m) {
                    $m->created_at = \Carbon\Carbon::parse($m->created_at)->format('d/m/y');

                    return $m;
                });
                break;
            case 'Monthly':
                $metings = $metings->map(function ($m) {
                    $m->created_at = \Carbon\Carbon::parse($m->created_at)->format('m/y');

                    return $m;
                });
                break;
            default:
                break;
        }

        return $metings;
    }

    /**
     * Aantal minuten boven x van poperty y by room.
     *
     * @return object (duration, property, above)
     */
    public static function TimeAboveByRoom(string $room, $param, $value)
    {
        return Cache::remember("time_above:${room}:${param}:${value}", 300, function () use ($room, $param, $value) {
            /**
             * select min(created_at), max(created_at), count(*) as numrecs, avg(temperature)
             * from ( select room,created_at, temperature,
             *  max(case when temperature < 18 then created_at end) over (order by created_at rows unbounded preceding) as prevlow
             * from metings where room = 130) as dt
             * where temperature >= 18
             * group by prevlow.
             */
            $result = DB::select("
                select min(created_at) as minimum, max(created_at) as maximum, count(*) as numrecs, avg({$param}) as average
                from ( select room,created_at, {$param},
                max(case when {$param} < ? then created_at end)
                over (order by created_at rows unbounded preceding) as prevlow
                from `metings` where room = ?) as dt
                where {$param} >= ?
                group by prevlow
                ", [$value, $room, $value]);

            $duration['property'] = $param;
            $duration['duration'] = 0;
            $duration['above'] = $value;

            foreach ($result as $res) {
                $duration['duration'] += Carbon::createFromDate($res->minimum)->diffInHours($res->maximum);
            }

            return $duration;
        });
    }

    /**
     * Get alle lokaalnummers.
     */
    public static function getRooms(): array
    {
        return Cache::remember('rooms', 300, fn () => Meting::distinct()->orderBy('room')->get(['room'])->pluck('room')->toArray());
    }

    public function scopeInterval($query, $interval = 'Realtime', $agg = 'avg')
    {
        /*
         *  300         // 5 minutes
         *  86400 / 24  // hourly
         *  86400       //day
         *  7 * 86400   //week
         *  31 * 86400  //month
         */

        switch ($interval) {
            case 'Hourly':
                $interval_unix = 86400 / 24;
                break;
            case 'Daily':
                $interval_unix = 86400;
                break;
            case 'Weekly':
                $interval_unix = 7 * 86400;
                break;
            case 'Monthly':
                $interval_unix = 31 * 86400;
                break;
            default:
                $interval_unix = 300;
                break;
        }

        //Min/Max/Average
        switch ($agg) {
            case 'Min':
            case 'min':
                $mma = 'min';
                break;
            case 'Max':
            case 'max':
                $mma = 'max';
                break;
            default:
                $mma = 'avg';
                break;
        }

        //select avg(co2) as co2, avg(temperature) as temperature, count(*) as count, min(created_at) as created_at, floor(UNIX_TIMESTAMP(created_at) / 86400 ) as my_interval from metings where room=101 group by my_interval;

        return $query
            ->toBase()
            ->selectRaw(
                "{$mma}(co2) as co2,".
                    "{$mma}(temperature) as temperature,".
                    "{$mma}(humidity) as humidity,".
                    'count(*) as count, '.
                    'min(created_at) as created_at, '.
                    'floor(UNIX_TIMESTAMP(created_at) / ? ) as my_interval',
                [$interval_unix]
            )
            ->groupBy('my_interval');
    }
}

app/Http/Controllers/API/MetingController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Meting;
use Illuminate\Http\JsonResponse;

class MetingController extends Controller
{
    public function store(): JsonResponse
    {
        $authorization = request()->header('authorization');

        if (empty($authorization)) {
            return response()->json(['message' => 'No api token provided']);
        }
        if ($authorization != env('SECRET_KEY')) {
            return response()->json(['message' => 'Invalid api token provided']);
        }

        request()->validate([
            'room' => 'required|integer|max:999|min:0',
            'co2' => 'required|integer|max:2000|min:10',
            'temperature' => 'required|integer|max:40|min:0',
            'humidity' => 'required|integer|max:100|min:0',
            'tvoc' => 'required|integer|max:2000|min:0',
        ]);

        Meting::create(request()->all());

        return response()
            ->json([
                'meting' => Meting::latest()->first(),
                'successful' => true,
            ], 201);
    }
}

app/Http/Controllers/MetingController.php
<?php

namespace App\Http\Controllers;

use App\Meting;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class MetingController extends Controller
{
    public function __construct()
    {
        //route protection on create/delete/edit
        $this->middleware('auth', ['except' => ['index', 'room', 'average']]);
    }

    public function index()
    {
        $latest = Meting::lastPerGroup(['room'])->orderBy('room')->paginate(12);
        $count = Meting::count();

        return view('metings.index', ['metings' => $latest, 'count' => $count]);
    }

    public function list()
    {
        $metings = Meting::latest()->paginate(8);

        return view('metings.list', compact('metings'))
            ->with('i', (request()->input('page', 1) - 1) * 8);
    }

    public function create()
    {
        return view('metings.create');
    }

    public function store(Request $request)
    {
        Meting::create($request->all());

        return redirect()->route('metings.list')
            ->with('success', 'Meting created successfully.');
    }

    public function show(Meting $meting)
    {
        /** get last records for this room */
        $latest = Meting::where('room', $meting->room)->get();

        return view('metings.show', ['meting' => $meting, 'latest' => $latest]);
    }

    /**
     * Display all metings for certain room.
     */
    public static function room(Request $request, string $room)
    {
        /**latest record based on room */
        $meting = Meting::getLatestByRoom($room);

        if (empty($meting)) {
            /* geen meting gevonden met ID */
            return abort(404);
        }

        /* axios call vanuit ChartComponent (in browser) gaat hierop returnen
         *  => nieuwe data zonder view te reloaden
         */
        if (request()->wantsJson()) {
            $interval = request()->get('interval');

            $latest = Meting::getPerIntervalByRoom($meting->room, $interval, ['format' => true]);

            return response($latest->values());
        }

        /** count number of metings for this room */
        $count = Meting::where('room', $meting->room)->count();

        $timeAboveData[] = ['data' => Meting::TimeAboveByRoom($room, 'co2', 250)];
        $timeAboveData[] = ['data' => Meting::TimeAboveByRoom($room, 'temperature', 10)];
        $timeAboveData[] = ['data' => Meting::TimeAboveByRoom($room, 'humidity', 10)];

        return view(
            'metings.room',
            [
                'meting' => $meting,
                'count' => $count,
                'timeAboveData' => $timeAboveData,
            ]
        );
    }

    public static function average()
    {
        /**latest record based on room */
        $avg = Meting::getLatestAverage();

        if (empty($avg)) {
            return abort(404);
        }

        return view(
            'metings.average',
            [
                'meting' => $avg,
                'roomnumbers' => Meting::getRooms(),
            ]
        );
    }

    public function edit(Meting $meting)
    {
        return view('metings.edit', compact('meting'));
    }

    public function update(Request $request, Meting $meting): RedirectResponse
    {
        $request->validate([
            'room' => 'required',
            'co2' => 'required',
            'temperature' => 'required',
        ]);

        $meting->update($request->all());

        return redirect()->route('metings.list')
            ->with('success', 'Meting updated successfully.');
    }

    public function destroy(Meting $meting): RedirectResponse
    {
        $meting->delete();

        return redirect()->route('metings.list')
            ->with('success', 'Meting deleted successfully');
    }
}

app/View/Components/MetingTable.php
<?php

namespace App\View\Components;

use App\Meting;
use Illuminate\View\Component;

class MetingTable extends Component
{
    public $meting;
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct(Meting $meting)
    {
        $this->meting = $meting;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\View\View|string
     */
    public function render()
    {
        return view('components.meting-table');
    }
}

resources/views/metings/average.blade.php
@extends('layouts.app')
@section('content')
<div class="text-center">
    <div class="mx-auto">
        <h2>{{ __('average') }}</h2>
        <x-meting-table :meting="$meting"></x-meting-table>
        <average-line-chart-component locale="{{ app()->getLocale() }}"></average-line-chart-component>
    </div>
</div>
@endsection

resources/views/metings/create.blade.php
@extends('layouts.app')

@section('content')
<div class="row text-center">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>{{ __('addMeting') }}</h2>
        </div>
    </div>
</div>

@if ($errors->any())
<div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif

<form action="{{ route('metings.store') }}" method="POST">
    @csrf

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>{{ __('room') }}:</strong>
                <input type="number" min="0" max="999" name="room" class="form-control" placeholder="room">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Co2:</strong>
                <input type="number" min="10" max="2000" class="form-control" name="co2" placeholder="600"></input>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>{{ __('humidity') }}:</strong>
                <input type="number" min="0" max="100" class="form-control" name="humidity" placeholder="50"></input>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>{{ __('temperature') }}:</strong>
                <input type="number" min="10" max="40" class="form-control" name="temperature" placeholder="20"></input>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-success">{{ __('submit') }}</button>
        </div>
    </div>

</form>
<div class="mt-5 container text-center">
    <div class="pull-right">
        <a class="btn btn-primary" href="{{ route('metings.index') }}">{{ __('back') }}</a>
    </div>
</div>
@endsection

resources/views/metings/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="row text-center">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>edit Meting {{ $meting->id }}</h2>
        </div>
    </div>
</div>

@if ($errors->any())
<div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif

<form action="{{ route('metings.update', $meting->id ) }}" method="POST">
    @csrf
    @method('PUT')

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>{{ __('room') }}:</strong>
                <input type="number" min="100" max="200" name="room" class="form-control" placeholder="room" value="{{ $meting->room }}">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Co2:</strong>
                <input type="number" min="0" max="2000" class="form-control" name="co2" placeholder="600" value="{{ $meting->co2 }}"></input>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>{{ __('humidity') }}:</strong>
                <input type="number" min="0" max="100" class="form-control" name="humidity" placeholder="50" value="{{ $meting->humidity }}"></input>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>{{ __('temperature') }}:</strong>
                <input type="number" min="10" max="40" class="form-control" name="temperature" placeholder="20" value="{{ $meting->temperature }}"></input>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-success">{{ __('submit') }}</button>
        </div>
    </div>

</form>
<div class="mt-5 container text-center">
    <div class="pull-right">
        <a class="btn btn-primary" href="{{ route('metings.list') }}"> {{ __('back') }}</a>
    </div>
</div>
@endsection

resources/views/metings/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="card-row">
        @forelse ($metings as $meting)
        <a href="{{ route('metings.room', $meting->room) }}" @if (!$meting->temperature_good || !$meting->humidity_good || !$meting->co2_good)
            data-html="true" data-toggle="tooltip" data-placement="top" title="{{ __('badValue') }}"
            @endif
            >
            <div class="col">
                <div class="card rounded overflow-hidden shadow-sm">
                    <div class="card-inner">
                        <div class="card-title">{{ __('room') }} {{ $meting->room }}
                            @if (!$meting->temperature_good || !$meting->humidity_good || !$meting->co2_good)
                            <span id="room-status-icon" style="float:right;" class="badge badge-pill">!</span>
                            @endif
                        </div>
                        <div class="card-value">CO&#8322;: {{ $meting->co2 }} ppm</div>
                        <div class="card-value">{{ __('humidity') }}: {{ $meting->humidity }} %</div>
                        <div class="card-value">{{ __('temperature') }}: {{ $meting->temperature }} °C</div>
                        <div class="card-value">{{ __('timestamp') }}: {{ $meting->created_at }}</div>
                    </div>
                </div>
            </div>
        </a>
        @empty
        <div>
            <div colspan="6">{{ __('noRecordsFound') }}</div>
        </div>
        @endforelse
    </div>
    <div class="container mt-3 justify-content-center">
        {{ $metings->links() }}
    </div>

    <div class="mt-5 text-center container">
        {{ __('numberOfRecords') }} {{ $count }}
    </div>
</div>
@endsection

resources/views/metings/list.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    @if ($message = Session::get('success'))
    <div class="alert alert-success">
        <p>{{ $message }}</p>
    </div>
    @endif
    <table class="table table-striped" style="max-width: 100%; font-size: 12px;">
        <thead class="thead-dark">
            <tr>
                <th>No</th>
                <th>id</th>
                <th>{{ __('room') }}</th>
                <th>Co2</th>
                <th>{{ __('humidity') }}</th>
                <th>{{ __('temperature') }}</th>
                <th>{{ __('createdAt') }}</th>
                <th width="215px">{{ __('action') }}</th>
            </tr>
        </thead>
        <tbody style="font-size: 18px">
            @foreach ($metings as $meting)

            <tr>
                <td>{{ ++$i }}</td>
                <td>{{ $meting->id }}</td>
                <td>{{ $meting->room }}</td>
                <td>{{ $meting->co2 }}</td>
                <td>{{ $meting->humidity }}</td>
                <td>{{ $meting->temperature }}</td>
                <td>{{ $meting->created_at }}</td>
                <td>
                    <form action="{{ route('metings.destroy', $meting->id ) }}" method="POST">

                        <a class="btn btn-primary" href="{{ route('metings.show', $meting->id ) }}">{{ __('show') }}</a>

                        <a class="btn btn-success" href="{{ route('metings.edit', $meting->id ) }}">{{ __('edit') }}</a>

                        @csrf
                        @method('DELETE')

                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
    {!! $metings->onEachSide(1)->links() !!}
</div>
@endsection

resources/views/metings/room.blade.php
@extends('layouts.app')
@section('content')
    <div class="text-center">
        <div>
            @if ($meting->time_since_last > 5)
                <div class="col-sm-12">
                    <div style="max-width: 400px" class="mx-auto alert alert-danger alert-dismissible fade show" role="alert">
                       {{ __('sensorOffline', ['minutes' => $meting->time_since_last])}}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                </div>
            @endif
            <h2> {{ __('room')}} {{ $meting->room }}</h2>
                <x-meting-table :meting="$meting"></x-meting-table>
                <div id="app">
                    <line-chart-component room="{{ $meting->room }}" locale="{{ app()->getLocale() }}"></line-chart-component>
                    <bar-chart-component room="{{ $meting->room }}"
                                         :timedata='@json($timeAboveData)'></bar-chart-component>
                </div>
        </div>
        @if (!empty($count))
            <div class="mt-5">
                {{ __('numberOfRecords') }} {{ $count }}
            </div>
        @endif
    </div>
@endsection

resources/views/metings/show.blade.php
@extends('layouts.app')
@section('content')
<div class="container text-center">
    <h2>Meting #{{ $meting->id }}</h2>
    <table class="table table-show">
        <tbody>
            <tr>
                <th>{{ __('room') }}</th>
                <td>{{ $meting->room }}</td>
            </tr>
            <tr>
                <th>Co2</th>
                <td>{{ $meting->co2 }}</td>
            </tr>
            <tr>
                <th>{{ __('humidity') }}</th>
                <td>{{ $meting->humidity }}</td>
            </tr>
            <tr>
                <th>{{ __('timestamp')}}</th>
                <td>{{ $meting->created_at }}</td>
            </tr>
        </tbody>
    </table>
</div>
<div class="mt-5 container text-center">
    <div class="pull-right">
        <a class="btn btn-primary" href="{{ route('metings.list') }}"> {{ __('back') }}</a>
    </div>
</div>
@endsection